from_json: ../data/redial/test.jsonl
to_json: mistral/general/redial_test.json
pretrained_model_name_or_path: mistralai/Mistral-7B-Instruct-v0.2
temperature: 0.0 
max_tokens: 512 
n_print: 100 
prompt: "Pretend you are a movie recommender system. \n I will give you a conversation between a user and you (a recommender system). Based on the conversation, you reply me with 20 recommendations without extra sentences.\n Here is the conversation: {}"
n_samples: -1 